version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-monitor"
s3_prefix = "crypto-monitor"
resolve_s3 = true
region = "us-west-2"
confirm_changeset = true
no_fail_on_empty_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
