version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-monitor"
s3_bucket = "crypto-monitor-source"
s3_prefix = "crypto-monitor"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
